# Generated by Django 3.2 on 2022-06-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
