# Generated by Django 3.2 on 2022-06-23 00:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file_name',
        ),
        migrations.AddField(
            model_name='image',
            name='file_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
