# Generated by Django 3.2 on 2022-06-23 21:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('thumbnails_sizes', models.JSONField(default=dict)),
                ('can_use_original_image_link', models.BooleanField(default=False)),
                ('can_fetch_expiring_link', models.BooleanField(default=False)),
                ('settings_hash', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
