# Generated by Django 3.2 on 2022-06-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_readonly_superuser",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
