# Generated by Django 3.2 on 2022-06-15 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 6, 15, 13, 4, 44, 659728, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="previous_user_tier",
            field=models.CharField(max_length=1000, verbose_name=2074664037792),
        ),
    ]
