# Generated by Django 3.2 on 2022-06-15 13:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20220615_1505"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstier",
            name="current_settings_hash",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 6, 15, 13, 16, 11, 141070, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="previous_user_tier",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.userstier",
            ),
        ),
    ]
