# Generated by Django 3.2 on 2022-06-15 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20220615_1516"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 6, 15, 13, 22, 19, 888736, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="userstier",
            name="can_fetch_expiring_link",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userstier",
            name="can_use_original_image_link",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userstier",
            name="thumbnail_sizes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
