# Generated by Django 3.2 on 2022-06-15 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20220615_1522"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userstier",
            old_name="current_settings_hash",
            new_name="settings_hash",
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 6, 15, 13, 32, 7, 93208, tzinfo=utc)
            ),
        ),
    ]
