# Generated by Django 3.2 on 2022-06-15 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20220615_1532"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UsersTier",
            new_name="UserTier",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="previous_user_tier",
            new_name="user_tier_settings_hash",
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 6, 15, 13, 42, 20, 291185, tzinfo=utc)
            ),
        ),
    ]
