# Generated by Django 3.2 on 2022-06-15 17:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_date_joined"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_tier_settings_hash",
            new_name="tier_settings_hash",
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 6, 15, 17, 28, 44, 532001, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.usertier",
            ),
        ),
    ]
