# Generated by Django 3.2 on 2022-06-15 17:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_auto_20220615_1928"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 6, 15, 17, 59, 52, 272642, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="usertier",
            name="thumbnail_sizes",
            field=models.JSONField(default=dict),
        ),
    ]
