# Generated by Django 3.2 on 2022-06-15 18:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_auto_20220615_2000"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertier",
            name="thumbnail_sizes",
        ),
        migrations.AddField(
            model_name="usertier",
            name="thumbnails_sizes",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 6, 15, 18, 26, 50, 304831, tzinfo=utc)
            ),
        ),
    ]
