# Generated by Django 3.2 on 2022-06-15 21:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 21, 43, 39, 712256, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_tier',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.usertier'),
        ),
    ]
