# Generated by Django 3.2 on 2022-06-15 21:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220615_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 21, 49, 38, 406650, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_tier',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.usertier'),
        ),
    ]
