# Generated by Django 3.2 on 2022-06-15 23:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20220615_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 23, 2, 29, 275603, tzinfo=utc)),
        ),
    ]
